---
# Send velocity commands from ROS → Gazebo
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/crazyflie/gazebo/command/twist"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

# Bridge the simulation clock from Gazebo → ROS
- ros_topic_name: "/clock"
  gz_topic_name: "/world/empty/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS


#  Pose (Gazebo → ROS)
- ros_topic_name: "/crazyflie/pose"
  gz_topic_name: "/model/crazyflie/pose"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS

# Odometry from Gazebo → ROS
- ros_topic_name: "/crazyflie/odom"
  gz_topic_name: "/model/crazyflie/odometry_with_covariance"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.OdometryWithCovariance"
  direction: GZ_TO_ROS
